name: firenotes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - 'assets/icons/'
