name: firenotes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  firebase_auth: 3.7.0
  firebase_core: 1.21.1
  firebase_storage: ^10.3.7
  flutter:
    sdk: flutter
  get: 4.6.5
  get_storage: ^2.0.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
